import { v4 as uuidv4 } from "uuid";

const statusStyles = {
    Confirmed: "bg-green-100 text-green-600 hover:bg-green-100",
    Pending: "bg-blue-100 text-blue-600 hover:bg-blue-100",
    Cancelled: "bg-red-100 text-red-600 hover:bg-red-100",
    "No-Show": "bg-yellow-100 text-yellow-600 hover:bg-yellow-100",
  };
  
// Define the data structure for attendees
interface Attendee {
    id: string;
    name: string;
    avatar: string;
    phone: string;
    email: string;
    class: string;
    instructor: {
      name: string;
      avatar: string;
    };
    status: keyof typeof statusStyles;
  }
  
  // Sample data for the table
  export const attendees: Attendee[] = [
    {
  id: uuidv4(),
      name: "John Doe",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "john@gmail.com",
      class: "Yoga",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Confirmed",
    },
    {
  id: uuidv4(),
      name: "Emily Smith",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 987 654 321",
      email: "emily@gmail.com",
      class: "HIIT",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
  id: uuidv4(),
      name: "Michael Brown",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 456 789 123",
      email: "michael@gmail.com",
      class: "Strength Training",
      instructor: {
        name: "Lisa Carter",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Cancelled",
    },
    {
  id: uuidv4(),
      name: "Liam Harris",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "liam@gmail.com",
      class: "Pilates",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "No-Show",
    },
    {
  id: uuidv4(),
      name: "Olivia Taylor",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "olivia@gmail.com",
      class: "CrossFit",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Confirmed",
    },
    {
  id: uuidv4(),
      name: "Isabella Scott",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "scott@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Confirmed",
    },
    {
  id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
  id: uuidv4(),
      name: "Liam Harris",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "liam@gmail.com",
      class: "Pilates",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "No-Show",
    },
    {
  id: uuidv4(),
      name: "Isabella Scott",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "scott@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Confirmed",
    },
    {
    id: uuidv4(),
      name: "John Doe",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "rhom@gmail.com",
      class: "Cardio Dance",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "kit@gmail.com",
      class: "Pilates",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Confirmed",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "kit@gmail.com",
      class: "Pilates",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Confirmed",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "John Doe",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "john@gmail.com",
      class: "Yoga",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Confirmed",
    },
    {
    id: uuidv4(),
      name: "Emily Smith",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 987 654 321",
      email: "emily@gmail.com",
      class: "HIIT",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Michael Brown",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 456 789 123",
      email: "michael@gmail.com",
      class: "Strength Training",
      instructor: {
        name: "Lisa Carter",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Cancelled",
    },
    {
    id: uuidv4(),
      name: "Liam Harris",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "liam@gmail.com",
      class: "Pilates",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "No-Show",
    },
    {
    id: uuidv4(),
      name: "Olivia Taylor",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "olivia@gmail.com",
      class: "CrossFit",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Confirmed",
    },
    {
    id: uuidv4(),
      name: "Isabella Scott",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "scott@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Confirmed",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Liam Harris",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "liam@gmail.com",
      class: "Pilates",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "No-Show",
    },
    {
    id: uuidv4(),
      name: "Isabella Scott",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "scott@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Confirmed",
    },
    {
    id: uuidv4(),
      name: "John Doe",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "rhom@gmail.com",
      class: "Cardio Dance",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "kit@gmail.com",
      class: "Pilates",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Confirmed",
    },
    {
  id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "kit@gmail.com",
      class: "Pilates",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Confirmed",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Isabella Scott",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "scott@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Confirmed",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Liam Harris",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "liam@gmail.com",
      class: "Pilates",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "No-Show",
    },
    {
    id: uuidv4(),
      name: "Isabella Scott",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "scott@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Confirmed",
    },
    {
    id: uuidv4(),
      name: "John Doe",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "rhom@gmail.com",
      class: "Cardio Dance",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "kit@gmail.com",
      class: "Pilates",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Confirmed",
    },
    {
  id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "kit@gmail.com",
      class: "Pilates",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Confirmed",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Isabella Scott",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "scott@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Confirmed",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Liam Harris",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "liam@gmail.com",
      class: "Pilates",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "No-Show",
    },
    {
    id: uuidv4(),
      name: "Isabella Scott",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "scott@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Confirmed",
    },
    {
    id: uuidv4(),
      name: "John Doe",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "rhom@gmail.com",
      class: "Cardio Dance",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "kit@gmail.com",
      class: "Pilates",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Confirmed",
    },
    {
  id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "kit@gmail.com",
      class: "Pilates",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Confirmed",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Isabella Scott",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "scott@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Confirmed",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Liam Harris",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "liam@gmail.com",
      class: "Pilates",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "No-Show",
    },
    {
    id: uuidv4(),
      name: "Isabella Scott",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "scott@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Confirmed",
    },
    {
    id: uuidv4(),
      name: "John Doe",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "rhom@gmail.com",
      class: "Cardio Dance",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "kit@gmail.com",
      class: "Pilates",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Confirmed",
    },
    {
  id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "kit@gmail.com",
      class: "Pilates",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Confirmed",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Isabella Scott",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "scott@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Confirmed",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Liam Harris",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "liam@gmail.com",
      class: "Pilates",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "No-Show",
    },
    {
    id: uuidv4(),
      name: "Isabella Scott",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "scott@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Confirmed",
    },
    {
    id: uuidv4(),
      name: "John Doe",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "rhom@gmail.com",
      class: "Cardio Dance",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "kit@gmail.com",
      class: "Pilates",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Confirmed",
    },
    {
  id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "kit@gmail.com",
      class: "Pilates",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Confirmed",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Isabella Scott",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "scott@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Confirmed",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Liam Harris",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "liam@gmail.com",
      class: "Pilates",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "No-Show",
    },
    {
    id: uuidv4(),
      name: "Isabella Scott",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "scott@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Confirmed",
    },
    {
    id: uuidv4(),
      name: "John Doe",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "rhom@gmail.com",
      class: "Cardio Dance",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "kit@gmail.com",
      class: "Pilates",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Confirmed",
    },
    {
  id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "kit@gmail.com",
      class: "Pilates",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Confirmed",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Isabella Scott",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "scott@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Confirmed",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Liam Harris",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "liam@gmail.com",
      class: "Pilates",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "No-Show",
    },
    {
    id: uuidv4(),
      name: "Isabella Scott",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "scott@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Confirmed",
    },
    {
    id: uuidv4(),
      name: "John Doe",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "rhom@gmail.com",
      class: "Cardio Dance",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "kit@gmail.com",
      class: "Pilates",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Confirmed",
    },
    {
  id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "kit@gmail.com",
      class: "Pilates",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Confirmed",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Isabella Scott",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "scott@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Confirmed",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Liam Harris",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "liam@gmail.com",
      class: "Pilates",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "No-Show",
    },
    {
    id: uuidv4(),
      name: "Isabella Scott",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "scott@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Confirmed",
    },
    {
    id: uuidv4(),
      name: "John Doe",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "rhom@gmail.com",
      class: "Cardio Dance",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "kit@gmail.com",
      class: "Pilates",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Confirmed",
    },
    {
  id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "kit@gmail.com",
      class: "Pilates",
      instructor: {
        name: "Sarah Johnson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Confirmed",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
    {
    id: uuidv4(),
      name: "Ava White",
      avatar: "https://github.com/shadcn.png",
      phone: "+1 234 567 890",
      email: "amile@gmail.com",
      class: "Zumba",
      instructor: {
        name: "Mark Robinson",
        avatar: "https://github.com/shadcn.png",
      },
      status: "Pending",
    },
  ];
  
  